/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as MyBirdsImport } from './routes/my-birds'
import { Route as AddBirdImport } from './routes/add-bird'
// import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const MyBirdsRoute = MyBirdsImport.update({
  path: '/my-birds',
  getParentRoute: () => rootRoute,
} as any)

const AddBirdRoute = AddBirdImport.update({
  path: '/add-bird',
  getParentRoute: () => rootRoute,
} as any)

// const AuthenticatedRoute = AuthenticatedImport.update({
//   id: '/_authenticated',
//   getParentRoute: () => rootRoute,
// } as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    // '/_authenticated': {
    //   preLoaderRoute: typeof AuthenticatedImport
    //   parentRoute: typeof rootRoute
    // }
    '/add-bird': {
      preLoaderRoute: typeof AddBirdImport
      parentRoute: typeof rootRoute
    }
    '/my-birds': {
      preLoaderRoute: typeof MyBirdsImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AddBirdRoute,
  MyBirdsRoute,
  SearchRoute,
])

/* prettier-ignore-end */
